# Generated by Django 5.2.6 on 2025-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('transport', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=4)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Other', 'Other')], max_length=20)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('admission_date', models.DateField()),
                ('reg_number', models.CharField(max_length=50, unique=True)),
                ('session', models.CharField(max_length=10)),
                ('character_cert', models.BooleanField(default=False)),
                ('report_card', models.BooleanField(default=False)),
                ('dob_cert', models.BooleanField(default=False)),
                ('last_school', models.CharField(blank=True, max_length=200)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam_result', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=10)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_qualification', models.CharField(blank=True, max_length=100)),
                ('father_dob', models.DateField(blank=True, null=True)),
                ('father_citizen', models.CharField(blank=True, max_length=50)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(blank=True, max_length=10)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_qualification', models.CharField(blank=True, max_length=100)),
                ('mother_dob', models.DateField(blank=True, null=True)),
                ('mother_citizen', models.CharField(blank=True, max_length=50)),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
