# Generated by Django 5.2.6 on 2025-09-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10, unique=True)),
                ('admission_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examination_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('library_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sports_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laboratory_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('computer_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_name'],
            },
        ),
    ]
