# Generated by Django 5.2.6 on 2025-09-18 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0003_remove_feestructure_total_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('selected_months', models.TextField()),
                ('fee_types', models.TextField()),
                ('custom_fees', models.TextField(blank=True)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('cheque_dd_no', models.CharField(blank=True, max_length=50)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmgmt.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
