# Generated by Django 5.2.6 on 2025-09-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0005_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
