# Generated by Django 5.2.6 on 2025-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0006_delete_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='class_name',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10, unique=True),
        ),
    ]
