# Generated by Django 5.2.6 on 2025-09-20 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0007_student_admission_paid_alter_feestructure_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('Mid Term', 'Mid Term'), ('Final Term', 'Final Term'), ('Unit Test', 'Unit Test'), ('Annual', 'Annual')], max_length=20)),
                ('class_name', models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('exam_date', models.DateField()),
                ('session', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('class_name', models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('max_marks', models.IntegerField(default=100)),
                ('pass_marks', models.IntegerField(default=35)),
            ],
            options={
                'ordering': ['class_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmgmt.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmgmt.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmgmt.subject')),
            ],
            options={
                'ordering': ['exam', 'student', 'subject'],
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
    ]
