# Generated by Django 5.2.6 on 2025-09-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0010_session_alter_exam_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('marks_obtained', models.IntegerField()),
                ('max_marks', models.IntegerField(default=100)),
                ('session', models.CharField(max_length=20)),
                ('exam_type', models.CharField(default='Regular', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmgmt.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'subject_name', 'session', 'exam_type')},
            },
        ),
    ]
