# Generated by Django 5.2.6 on 2025-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0011_studentmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('marks_obtained', models.IntegerField()),
                ('max_marks', models.IntegerField(default=100)),
                ('session', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
