# Generated by Django 5.2.6 on 2025-09-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0012_marksheetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('performance', models.CharField(max_length=20)),
                ('grade_point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-min_marks'],
            },
        ),
    ]
