# Generated by Django 5.2.6 on 2025-09-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0015_enhance_nepali_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_date_nepali_short',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_date_nepali',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_date_nepali',
        ),
    ]
