# Generated by Django 5.2.6 on 2025-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0016_auto_20250924_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_date_nepali',
            field=models.CharField(blank=True, help_text='Nepali date format', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date_nepali',
            field=models.CharField(blank=True, help_text='Nepali date format', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date_nepali_short',
            field=models.CharField(blank=True, help_text='Short Nepali date (YYYY/MM/DD)', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='dob_nepali',
            field=models.CharField(blank=True, help_text='Format: YYYY/MM/DD', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_dob_nepali',
            field=models.CharField(blank=True, help_text='Format: YYYY/MM/DD', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_dob_nepali',
            field=models.CharField(blank=True, help_text='Format: YYYY/MM/DD', max_length=20),
        ),
    ]
