# Generated by Django 5.2.6 on 2025-09-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0018_alter_feestructure_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['class_order']},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_order',
            field=models.IntegerField(default=0, help_text='Order for sorting classes'),
        ),
    ]
