# Generated by Django 5.2.6 on 2025-09-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0019_alter_feestructure_options_feestructure_class_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='bill_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
