# Generated by Django 5.2.6 on 2025-09-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0020_feepayment_bill_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='bill_filename',
        ),
        migrations.CreateModel(
            name='StudentDailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmgmt.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
