# Generated by Django 5.2.6 on 2025-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0021_remove_feepayment_bill_filename_studentdailyexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Everest Academy', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Detail',
                'verbose_name_plural': 'School Details',
            },
        ),
    ]
