# Generated by Django 5.2.6 on 2025-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0023_auto_20250928_0226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDCardTemplate',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
