# Generated by Django 5.2.6 on 2025-09-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0024_delete_idcardtemplate_delete_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='subashgongwanepal@gmail.com', max_length=254),
        ),
    ]
