# Generated by Django 5.2.6 on 2025-09-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0027_studentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='student_class',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten'), ('Eleven', 'Eleven'), ('Twelve', 'Twelve')], max_length=10),
        ),
    ]
