# Generated by Django 4.2.7 on 2024-12-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0032_welcomesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='status',
            field=models.CharField(default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]