# Generated by Django 5.2.6 on 2025-09-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0033_auto_20250929_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='updated_at',
        ),
    ]
