# Generated by Django 5.2.6 on 2025-09-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0035_add_contactenquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]