# Generated by Django 5.2.6 on 2025-10-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0038_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten'), ('Eleven', 'Eleven'), ('Twelve', 'Twelve'), ('All Classes', 'All Classes')], help_text='Primary class assigned to teach', max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_specialization',
            field=models.CharField(blank=True, help_text='Main subject specialization', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(blank=True, help_text='All subjects taught (comma separated)', max_length=200),
        ),
    ]
