# Generated by Django 5.2.6 on 2025-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0039_teacher_assigned_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('Social Studies', 'Social Studies'), ('Computer Science', 'Computer Science'), ('Arts', 'Arts'), ('Physical Education', 'Physical Education'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
