# Generated by Django 5.2.6 on 2025-10-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0040_subject_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_specialization',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.CreateModel(
            name='TeacherClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten'), ('Eleven', 'Eleven'), ('Twelve', 'Twelve')], max_length=15)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary class for this teacher?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmgmt.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='schoolmgmt.teacher')),
            ],
            options={
                'ordering': ['teacher__name', 'class_name', 'subject__name'],
                'unique_together': {('teacher', 'class_name', 'subject')},
            },
        ),
    ]
