# Generated by Django 5.2.6 on 2025-10-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0041_remove_teacher_assigned_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherclasssubject',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='teacherclasssubject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this assignment currently active?'),
        ),
        migrations.AddField(
            model_name='teacherclasssubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
