# Generated by Django 5.2.6 on 2025-10-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0042_remove_teacherclasssubject_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Head Teacher', 'Head Teacher'), ('Senior Teacher', 'Senior Teacher'), ('Teacher', 'Teacher'), ('Assistant Teacher', 'Assistant Teacher'), ('Subject Teacher', 'Subject Teacher'), ('Accountant', 'Accountant'), ('Office Assistant', 'Office Assistant'), ('Librarian', 'Librarian'), ('Lab Assistant', 'Lab Assistant'), ('Computer Operator', 'Computer Operator'), ('Security Guard', 'Security Guard'), ('Kitchen Staff', 'Kitchen Staff'), ('Cleaner', 'Cleaner'), ('Driver', 'Driver'), ('Maintenance Staff', 'Maintenance Staff'), ('Nurse', 'Nurse'), ('Counselor', 'Counselor'), ('Sports Instructor', 'Sports Instructor')], max_length=50),
        ),
    ]
