# Generated by Django 5.2.6 on 2025-10-01 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0043_alter_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to='schoolmgmt.teacher'),
        ),
    ]
