# Generated by Django 5.2.6 on 2025-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0044_adminlogin_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='can_create_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_delete_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Can create and delete users'),
        ),
    ]
