# Generated by Django 5.2.6 on 2025-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0045_adminlogin_can_create_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_charts',
            field=models.BooleanField(default=True, help_text='Can view dashboard charts'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_dashboard',
            field=models.BooleanField(default=True, help_text='Can view main dashboard'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_stats',
            field=models.BooleanField(default=True, help_text='Can view dashboard statistics'),
        ),
    ]
