# Generated by Django 5.2.6 on 2025-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0046_adminlogin_can_view_charts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_expenses',
            field=models.BooleanField(default=True, help_text='Can view daily expenses menu'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_fees',
            field=models.BooleanField(default=True, help_text='Can view fee structure menu'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_marksheet',
            field=models.BooleanField(default=True, help_text='Can view marksheet menu'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_receipts',
            field=models.BooleanField(default=True, help_text='Can view fee receipts menu'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_reports',
            field=models.BooleanField(default=True, help_text='Can view reports menu'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_settings',
            field=models.BooleanField(default=True, help_text='Can view settings menus'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_students',
            field=models.BooleanField(default=True, help_text='Can view students menu'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_teachers',
            field=models.BooleanField(default=True, help_text='Can view teachers menu'),
        ),
    ]
