# Generated by Django 5.2.6 on 2025-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0047_adminlogin_can_view_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='can_view_charts',
        ),
        migrations.RemoveField(
            model_name='adminlogin',
            name='can_view_expenses',
        ),
        migrations.RemoveField(
            model_name='adminlogin',
            name='can_view_fees',
        ),
        migrations.RemoveField(
            model_name='adminlogin',
            name='can_view_receipts',
        ),
        migrations.RemoveField(
            model_name='adminlogin',
            name='can_view_settings',
        ),
        migrations.RemoveField(
            model_name='adminlogin',
            name='can_view_stats',
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_daily_expenses',
            field=models.BooleanField(default=True, help_text='Can view daily expenses menu', verbose_name='Daily Expenses'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_fee_receipt',
            field=models.BooleanField(default=True, help_text='Can view fee receipt menu', verbose_name='Fee Receipt'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_fee_structure',
            field=models.BooleanField(default=True, help_text='Can view fee structure menu', verbose_name='Fee Structure'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_school_settings',
            field=models.BooleanField(default=True, help_text='Can view school settings menu', verbose_name='School Settings'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_user_management',
            field=models.BooleanField(default=True, help_text='Can view user management menu', verbose_name='User Management'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_website_settings',
            field=models.BooleanField(default=True, help_text='Can view website settings menu', verbose_name='Website Settings'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_dashboard',
            field=models.BooleanField(default=True, help_text='Can view dashboard', verbose_name='Dashboard'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_marksheet',
            field=models.BooleanField(default=True, help_text='Can view marksheet menu', verbose_name='Marksheet'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_reports',
            field=models.BooleanField(default=True, help_text='Can view reports menu', verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_students',
            field=models.BooleanField(default=True, help_text='Can view students menu', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_teachers',
            field=models.BooleanField(default=True, help_text='Can view teachers menu', verbose_name='Teachers'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='password',
            field=models.CharField(help_text='Plain text password (no hashing)', max_length=100),
        ),
    ]
