# Generated by Django 5.2.6 on 2025-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0048_remove_adminlogin_can_view_charts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_charts',
            field=models.BooleanField(default=True, help_text='Can view charts and graphs', verbose_name='Charts'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_expenses',
            field=models.BooleanField(default=True, help_text='Can view expenses menu', verbose_name='Expenses'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_fees',
            field=models.BooleanField(default=True, help_text='Can view fees menu', verbose_name='Fees'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_receipts',
            field=models.BooleanField(default=True, help_text='Can view receipts menu', verbose_name='Receipts'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_settings',
            field=models.BooleanField(default=True, help_text='Can view settings menu', verbose_name='Settings'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_stats',
            field=models.BooleanField(default=True, help_text='Can view statistics', verbose_name='Statistics'),
        ),
    ]
