# Generated by Django 5.2.6 on 2025-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0049_adminlogin_can_view_charts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='can_view_attendance',
            field=models.BooleanField(default=True, help_text='Can view student attendance menu', verbose_name='Student Attendance'),
        ),
    ]
