# Generated by Django 5.2.6 on 2025-10-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0051_auto_20251003_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_for',
            field=models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten'), ('Eleven', 'Eleven'), ('Twelve', 'Twelve')], help_text='Class for which this teacher is the class teacher', max_length=15, null=True),
        ),
    ]
