# Generated by Django 5.2.6 on 2025-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0052_teacher_class_teacher_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='can_edit_own_class_marksheet',
            field=models.BooleanField(default=True, help_text='Can edit marksheet data for assigned classes/subjects', verbose_name='Edit Own Class Marksheet'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_attendance',
            field=models.BooleanField(default=False, help_text='Can view student attendance menu', verbose_name='Student Attendance'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_charts',
            field=models.BooleanField(default=False, help_text='Can view charts and graphs', verbose_name='Charts'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_daily_expenses',
            field=models.BooleanField(default=False, help_text='Can view daily expenses menu', verbose_name='Daily Expenses'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_dashboard',
            field=models.BooleanField(default=False, help_text='Can view dashboard', verbose_name='Dashboard'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_expenses',
            field=models.BooleanField(default=False, help_text='Can view expenses menu', verbose_name='Expenses'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_fee_receipt',
            field=models.BooleanField(default=False, help_text='Can view fee receipt menu', verbose_name='Fee Receipt'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_fee_structure',
            field=models.BooleanField(default=False, help_text='Can view fee structure menu', verbose_name='Fee Structure'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_fees',
            field=models.BooleanField(default=False, help_text='Can view fees menu', verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_marksheet',
            field=models.BooleanField(default=False, help_text='Can view marksheet menu', verbose_name='Marksheet'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_receipts',
            field=models.BooleanField(default=False, help_text='Can view receipts menu', verbose_name='Receipts'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can view reports menu', verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_school_settings',
            field=models.BooleanField(default=False, help_text='Can view school settings menu', verbose_name='School Settings'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_settings',
            field=models.BooleanField(default=False, help_text='Can view settings menu', verbose_name='Settings'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_stats',
            field=models.BooleanField(default=False, help_text='Can view statistics', verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_user_management',
            field=models.BooleanField(default=False, help_text='Can view user management menu', verbose_name='User Management'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='can_view_website_settings',
            field=models.BooleanField(default=False, help_text='Can view website settings menu', verbose_name='Website Settings'),
        ),
    ]
