# Generated by Django 5.2.6 on 2025-10-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0053_adminlogin_can_edit_own_class_marksheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('event_date_nepali', models.CharField(blank=True, help_text='Nepali date format', max_length=50)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('festival', 'Festival'), ('exam', 'Exam'), ('meeting', 'Meeting'), ('event', 'School Event'), ('other', 'Other')], default='event', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
