# Generated by Django 5.2.6 on 2025-10-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0056_schoolattendance'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS schoolmgmt_studentattendance;",
            reverse_sql="CREATE TABLE schoolmgmt_studentattendance (id INTEGER PRIMARY KEY);"
        ),
    ]
