# Generated by Django 5.2.6 on 2025-10-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0057_create_schoolattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdailyexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdailyexpense',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
