# Generated by Django 5.2.6 on 2025-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmgmt', '0058_studentdailyexpense_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, help_text='Student login password', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, help_text='Student login username', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('festival', 'Festival'), ('exam', 'Exam'), ('meeting', 'Meeting'), ('event', 'School Event'), ('school-day', 'School Day'), ('other', 'Other')], default='event', max_length=20),
        ),
    ]
